### ISSUE TITLE
pod search 'YNPageViewController'搜索不到

### ISSUE THREAD

**Issue by SunsgneDZ** [yongyuandouneng/YNPageViewController#1]
pod是不是有点问题...

**Comment by SunsgneDZ** [comment]
搜索 'YNPage'发现一个'YNPageScrollViewController'
是不是就是这个

**Comment by yongyuandouneng** [comment]
pod setup` 再搜  pod search YNPageViewController

**Comment by yongyuandouneng** [comment]
1. pod repo update 2.rm ~/Library/Caches/CocoaPods/search_index.json
