### ISSUE TITLE
YNPageStyleSuspensionCenter

### ISSUE THREAD

**Issue by ellmcz** [yongyuandouneng/YNPageViewController#14]
YNPageStyleSuspensionCenter 第一次， vc.pageIndex = 0;，进去就到标题，头部不能显示，点击1的时候，正常了。

**Comment by yongyuandouneng** [comment]
我刚尝试了是好的，麻烦你加群录制一个gif哈。

**Comment by ellmcz** [comment]
和这个框架DZNEmptyDataSet 冲突

**Comment by yongyuandouneng** [comment]
需要用 cell 做 无数据图和占位图·
