### ISSUE TITLE
视图层级问题

### ISSUE THREAD

**Issue by changsanjiang** [yongyuandouneng/YNPageViewController#16]
https://github.com/yongyuandouneng/YNPageViewController/blob/6743821bf972206743e3a3886a50f05b0e42092d/YNPageViewController/YNPageViewController/Libs/YNPageViewController/YNPageViewController.m#L757

当移除这两个视图(`self.headerBgView`&`self.scrollMenuView`), 直接add到`self.view`时, 视图层级会出现点问题(原本在self.view最上层的视图, 会被刚add上去的这两货挡住). 是否可以修改成如下代码:
```Objective-C
 [self.view insertSubview:self.headerBgView aboveSubview:self.pageScrollView];
 [self.view insertSubview:self.scrollMenuView aboveSubview:self.headerBgView];
```

**Comment by yongyuandouneng** [comment]
好。

**Comment by changsanjiang** [comment]
Thanks. that's great lib.
