### ISSUE TITLE
与tableviewcell左滑删除的手势冲突

### ISSUE THREAD

**Issue by BeihaoZhang** [yongyuandouneng/YNPageViewController#17]
无法触发tableViewCell左滑删除手势

**Comment by yongyuandouneng** [comment]
嵌套scrollview的都有这个问题...

**Comment by BeihaoZhang** [comment]
这个在你这个框架的基础上怎么解决呢？我本想通过(YNPageViewController*)pageVC.bgScrollView.scrollEnabled = NO;禁用左右滑动的，但是没有效果
在 2018年8月14日 +0800 AM10:10，郑永能 <notifications@github.com>，写道：

**Comment by BeihaoZhang** [comment]
能否把这个属性暴露出来呢，然后我更新下pod😆
在 2018年8月14日 +0800 AM10:33，郑永能 <notifications@github.com>，写道：

**Comment by yongyuandouneng** [comment]
更新看看 0.1.8 的 config
