### ISSUE TITLE
问题:如果数据都是从网络获取的怎么处理

### ISSUE THREAD

**Issue by gjcbo** [yongyuandouneng/YNPageViewController#5]
不好用的地方:
1.禁用了  init 感觉不太好。
+ (instancetype)new UNAVAILABLE_ATTRIBUTE;
- (instancetype)init UNAVAILABLE_ATTRIBUTE;

2.对于这样的需求无能为力:部分数据是从网络(轮播图的数组+轮播图下面的标题文字数组都是从网络获取的)这种情况就不好处理。正常的逻辑先创建控制器。在控制器的viewDidLoad方法中进行网络请求,请求到数据之后刷新数据。(先有VC再有数据) 。但是提供的接口是:先有数据才能创建VC。 
+ (instancetype)pageViewControllerWithControllers:(NSArray *)controllers
                                           titles:(NSArray *)titles
                                           config:(YNPageConfigration *)config;

3. 总体感觉还是挺👍的。

**Comment by yongyuandouneng** [comment]
请看Demos 的 加载数据后显示页面

**Comment by gjcbo** [comment]
ok
