### ISSUE TITLE
YNPageViewController 控制器内调用scrollViewDidScroll:(UIScrollView *)scrollView 会导致子控制器页面布局失效

### ISSUE THREAD

**Issue by rychopper** [yongyuandouneng/YNPageViewController#68]
demo中在BasePageViewController 调用(void)scrollViewDidScroll:(UIScrollView *)scrollView，相关的子页面布局都会失效，出现空白页面

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
