### ISSUE TITLE
关于导航条隐藏的适配

### ISSUE THREAD

**Issue by fuyunmanbu** [yongyuandouneng/YNPageViewController#7]
![snip20180709_1](https://user-images.githubusercontent.com/16368126/42443633-9dfeb784-83a0-11e8-9b99-0ea5e5dc00f4.png)

**Comment by yongyuandouneng** [comment]
把高度调大么？ 这个你想怎么视频...

**Comment by fuyunmanbu** [comment]
这个，当选择框滑动到接近状态栏的时候，状态栏背景自动渐变成不透明，默认白色，造成选择框被阻挡的效果，不至于成这样，可以实现这种适配嘛？😁

**Comment by yongyuandouneng** [comment]
暂不做这个处理...

**Comment by fuyunmanbu** [comment]
那有没有可以控制选择框在某个位置就开始悬浮的

**Comment by fuyunmanbu** [comment]
你可能领会错了我的意思，我是指可不可以控制选择框悬浮的位置，而不是控制从哪里开始悬浮，而悬浮的位置还是老位置

**Comment by yongyuandouneng** [comment]
@fuyunmanbu 忘记跟你说了 这个可以的了。

**Comment by cwwise** [comment]
怎么设置呢
